apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: nodejs-micro-example
manifests:
  rawYaml:
    - infra/k8s-dev/*
build:
  platforms:
    - "linux/amd64"
    - "linux/arm64"
  local:
    push: false
  artifacts:
    - image: faridmansimli/micro-account
      context: account
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    
    - image: faridmansimli/micro-auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: src/**/*.ts
            dest: .
    
    - image: faridmansimli/micro-places
      context: places
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: src/**/*.ts
            dest: .

deploy:
  kubectl:
    remoteManifests:
      - infra/k8s-prod/*
  
