apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-events-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-events
  template:
    metadata:
      labels:
        app: micro-events
    spec:
      containers:
        - name: micro-events-cont
          image: faridmansimli/micro-events
          ports:
            - containerPort: 4003
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: NODE_ENV
              value: development
            
            - name: APP_NAME
              value: micro-events
            
            - name: APP_HOST
              value: micro-events-srv
            
            - name: PORT
              value: "4003"

            - name: MONGO_HOST
              value: micro-events-db-srv
              
            - name: MONGO_PORT
              value: "27017"

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-user
                  key: MONGO_USER

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD
            
            - name: MONGO_DB
              value: eventsdb

---
apiVersion: v1
kind: Service
metadata: 
  name: micro-events-srv
spec:
  type: ClusterIP
  selector:
    app: micro-events
  ports:
    - name: micro-events-port
      protocol: TCP
      port: 4003
      targetPort: 4003