apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-places-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-places-db
  template:
    metadata:
      labels:
        app: micro-places-db
    spec:
      volumes:
        - name: micro-places-db-storage
          persistentVolumeClaim:
            claimName: micro-places-db-pvc
      containers:
        - name: micro-places-db-cont
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: micro-places-db-storage
              mountPath: /data/db

          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: MONGO_INITDB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-user
                  key: MONGO_USER
            
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: MONGO_PASSWORD

            - name: MONGO_INITDB_DATABASE
              value: authdb
---
apiVersion: v1
kind: Service
metadata:
  name: micro-places-db-srv
spec:
  type: ClusterIP
  selector:
    app:  micro-places-db
  ports:
    - name: micro-places-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micro-places-db-pvc
spec:
  resources:
    requests:
      storage: "500Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
