apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-zookeeper-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-zookeeper
  template:
    metadata:
      labels:
        app: micro-zookeeper
    spec:
      volumes:
        - name: micro-zookeeper-storage
          persistentVolumeClaim:
            claimName: micro-zookeeper-pvc
      containers:
        - name: micro-zookeeper-cont
          image: bitnami/zookeeper
          ports:
            - containerPort: 2181
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          volumeMounts:
            - name: micro-zookeeper-storage
              mountPath: /bitnami
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: yes

---
apiVersion: v1
kind: Service
metadata:
  name: micro-zookeeper-srv
spec:
  type: ClusterIP
  selector:
    app: micro-zookeeper
  ports:
    - name: micro-zookeeper-port
      protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micro-zookeeper-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
